[package]
name = "ws-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
futures = "0.3.31"
url = "2.5.0"
http = "1.0.0"
tracing = "0.1.41"